# Generated by Django 5.0.1 on 2024-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project_photo',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
